### ISSUE TITLE
Custom templates doesn't work

### ISSUE THREAD

**Issue by jayhahn** [michaelbromley/ng2-pagination#12]
I copy pasted your custom templates example but it throws an error

TypeError: l_p4.isFirstPage is not a function in [p.isFirstPage() in MyAppComponent@47:57]

**Comment by jayhahn** [comment]
Also, PaginationControlsCmp seems to have been renamed to PAGINATION_DIRECTIVES?
Looks like the readme and examples haven't been updated to reflect that.

**Comment by michaelbromley** [comment]
Hi,

Are you using the latest version (beta.2)? I pushed an update yesterday which had a breaking change in the way custom templates work. `PAGINATION_DIRECTIVES` is no longer exported, you just need `PaginationControlsCmp`. See the readme and changelog for details. 

Please check the version and close if fixed, or show me the code you are using if the problem persists.

**Comment by jayhahn** [comment]
@michaelbromley 

I was using beta.1. I just tried it with beta.2 which seemed to have changed back to PaginationControlsCmp but custom templates still doesn't work if pagination-control is before the content.

Expression 'p.isFirstPage() in MyAppComponent@50:53' has changed after it was checked. Previous value: 'false'. Current value: 'true' in [p.isFirstPage() in MyAppComponent@50:53]

It works as intended if you keep the pagination-control after the content. Perhaps a related issue with issue #6 ?

**Comment by michaelbromley** [comment]
Okay, I will check this out and write a unit test for this case.

**Comment by michaelbromley** [comment]
I cannot recreate your error. In the demo app in this repo, if I put the `<pagination-controls>` before the PaginatePipe, I don't see any exception.

Could you show me your code so I can try to reproduce it?

Ideally I would like to provide a way to make live demos on Plunker - I need to figure out how to provide a systemjs bundle first though.

**Comment by michaelbromley** [comment]
@jayhahn Please see [this plunker demo](http://plnkr.co/edit/SDwkBWrp6NnJ5x1FP6Y5?p=preview) which shows a custom template being used before the `ngFor` in the page.
